---
collections:
  - name: ansible.netcommon
    version: 2.5.1

  - name: community.docker
    version: 3.2.1

  - name: community.general

  - name: community.zabbix
    version: 1.7.0

  - name: community.mysql
    version: 3.1.0

  - name: community.hashi_vault
    version: '>=4.0.0'

  - name: citrix.adc
    version: 1.1.0

  - name: ansible.controller
    version: 4.3.0
